ACHE.Admin/Controllers/LogAfipController.cs
using ACHE.Admin.Models;
using ACHE.Extensions;
using ACHE.Model;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.SqlServer;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace ACHE.Admin.Controllers
{
    public class LogAfipController : BaseController
    {
        // GET: LogAfip
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ObtenerLog(string cuit, string take)
        {
            ResultadosLogAfipViewModel resultado = new ResultadosLogAfipViewModel();

            try
            {
                using (var dbContext = new ACHEEntities())
                {

                     List<vLogServicios> results;

                    if (cuit.Equals("NuN")) {                        
                        results = dbContext.vLogServicios.OrderByDescending(x => x.IDLogServicio).Take(Convert.ToInt32(take)).ToList();
                    } else {
                        results = dbContext.vLogServicios.Where(c => c.CUIT == cuit).OrderByDescending(x => x.IDLogServicio).Take(Convert.ToInt32(take)).ToList();
                    }                    

                    var list = results.ToList()
                             .Select(x => new LogAfipViewModel()
                             {
                                 ID = x.IDLogServicio,
                                 Entidad = x.Entidad,
                                 Url = x.Url.Length > 10 ? x.Url.Substring(0, 10) + "..." : x.Url,
                                 Nombre = x.Nombre,
                                 Mensaje = x.Mensaje.Length > 10 ? x.Mensaje.Substring(0, 10) + "..." : x.Mensaje,
                                 FechaEmision = x.FechaEmision,
                                 UsuarioCUIT = x.CUIT,
                                 RazonSocial = x.RazonSocial,
                                 Envio = x.Envio,
                                 Respuesta = x.Respuesta.Length > 10 ? x.Respuesta.Substring(0, 10) + "..." : x.Respuesta,
                                 RespuestaExitosa = x.RespuestaExitosa,
                                 FechaRespuesta = x.FechaRespuesta
                             });
                    resultado.Items = list.ToList();
                }
            }
            catch (Exception)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        // GET: LogAfip
        public ActionResult View(int id)
        {
            var dbContext = new ACHEEntities();

            vLogServicios v = dbContext.vLogServicios.Where(x => x.IDLogServicio == id).FirstOrDefault();

            v.Respuesta = PrintXML(v.Respuesta.Trim());

            return View(v);
        }


        public static string PrintXML(string xml)
        {
            string result = "";

            MemoryStream mStream = new MemoryStream();
            XmlTextWriter writer = new XmlTextWriter(mStream, Encoding.Unicode);
            XmlDocument document = new XmlDocument();

            try
            {
                // Load the XmlDocument with the XML.
                document.LoadXml(xml);

                writer.Formatting = Formatting.Indented;

                // Write the XML into a formatting XmlTextWriter
                document.WriteContentTo(writer);
                writer.Flush();
                mStream.Flush();

                // Have to rewind the MemoryStream in order to read
                // its contents.
                mStream.Position = 0;

                // Read MemoryStream contents into a StreamReader.
                StreamReader sReader = new StreamReader(mStream);

                // Extract the text from the StreamReader.
                string formattedXml = sReader.ReadToEnd();

                result = formattedXml;
                return result;
            }
            catch (XmlException)
            {
                return xml;
            }
        }
    }
}

ACHE.Admin/Controllers/SoporteController.cs
using System;
using System.Configuration;
using System.Web.Mvc;
using ACHE.Model;
using ACHE.Negocio.Facturacion;


namespace ACHE.Admin.Controllers
{
    public class SoporteController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RecuperarComprobante(string nroComprobante, string cuitUsuario, string tipoComprobante, int punto)
        {
            var dto = new ErrorViewModel();
            try
            {
                var existe = ComprobantesCommon.ExisteComprobante(Convert.ToInt64(cuitUsuario), Convert.ToInt64(nroComprobante), punto, tipoComprobante);
                if (!existe)
                {
                    long cuitRep = Convert.ToInt64(ConfigurationManager.AppSettings["FE.QA.CUIL"]);
                    var comprobante = ComprobantesCommon.ObtenerComprobanteElectronica(Convert.ToInt64(cuitUsuario), cuitRep, Convert.ToInt64(nroComprobante), punto, tipoComprobante);
                    ComprobantesCommon.InsertarComprobanteRecuperado(comprobante, tipoComprobante, cuitUsuario.ToString());
                    dto.TieneError = false;
                }
                else
                {
                    dto.TieneError = true;
                    dto.Mensaje = "Ya exise un comprobante para los datos seleccionados.";
                }
            }
            catch (Exception ex)
            {
                dto.TieneError = true;
                dto.Mensaje = ex.Message;
            }

            return Json(dto, JsonRequestBehavior.AllowGet);
        }
    }
}

ACHE.Admin/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ACHE.Model;
using ACHE.Extensions;
using ACHE.Admin.Models;
using System.Configuration;
using System.Collections.Specialized;
using System.Data;
using System.IO;
using ACHE.Negocio.Facturacion;
using ACHE.Model.Negocio;
using ACHE.Negocio.Common;
using ACHE.Negocio.Contabilidad;
using ACHE.Model.ViewModels;
using System.Text;
using System.Security.Cryptography;
using System.Data.SqlClient;
using System.Web;
using Newtonsoft.Json;

namespace ACHE.Admin.Controllers
{
    public class UsuarioController : BaseController
    {
        public ActionResult Index(int idPlan = 0, string estado = "")
        {
            if (idPlan > 0 && !string.IsNullOrWhiteSpace(estado))
            {
                var model = new PlanesViewModel();
                model.Estado = estado;
                switch (idPlan)
                {
                    case 1:
                        model.Plan = "Basico";
                        break;
                    case 2:
                        model.Plan = "Profesional";
                        break;
                    case 3:
                        model.Plan = "Pyme";
                        break;
                    case 4:
                        model.Plan = "Empresa";
                        break;
                    case 5:
                        model.Plan = "Corporativo";
                        break;
                    case 6:
                        model.Plan = "Prueba";
                        break;
                }
                return View(model);
            }
            else
                return View();
        }



        public ActionResult Edicion(int id)
        {
            var model = new UsuarioViewModel();
            using (var dbContext = new ACHEEntities())
            {
                model = dbContext.Usuarios.Include("PlanesPagos").Where(x => x.IDUsuario == id).Select(x => new UsuarioViewModel()
                {
                    ID = x.IDUsuario,
                    RazonSocial = x.RazonSocial,
                    CondicionIva = x.CondicionIva,
                    CUIT = x.CUIT,
                    Telefono = x.Telefono,
                    Email = x.Email,
                    EsAgentePercepcionIIBB = (x.EsAgentePercepcionIIBB == null) ? false : (bool)x.EsAgentePercepcionIIBB,
                    EsAgentePercepcionIVA = (x.EsAgentePercepcionIVA == null) ? false : (bool)x.EsAgentePercepcionIVA,
                    EsAgenteRetencion = (x.EsAgenteRetencion == null) ? false : (bool)x.EsAgenteRetencion,
                    MercadoPagoClientSecret = x.MercadoPagoClientSecret,
                    MercadoPagoClientID = x.MercadoPagoClientID,
                    SetupRealizado = x.SetupRealizado ? "SI" : "NO",
                    ApiKey = x.ApiKey,
                    TemplateFc = x.TemplateFc,
                    Celular = x.Celular,
                    IIBB = x.IIBB,
                    Activo = x.Activo,
                    EmailAlertas = x.EmailAlertas,
                    TieneFacturaElectronica = x.TieneFacturaElectronica,
                    FechaAlta = x.FechaAlta,
                    FechaInicioActividades = (x.FechaInicioActividades == null) ? DateTime.Now : (DateTime)x.FechaInicioActividades,
                    CodigoPostal = x.CodigoPostal,
                    CodigoPromo = x.CodigoPromo,
                    Domicilio = x.Domicilio,
                    Contacto = x.Contacto,
                    CorreoPortal = x.CorreoPortal,
                    FechaFinPlan = x.FechaFinPlan,
                    IDCiudad = x.IDCiudad,
                    Personeria = x.Personeria,
                    PisoDepto = x.PisoDepto,
                    Logo = x.Logo,
                    //FechaUltLogin = x.FechaUltLogin.ToString("dd/MM/yyyy"),
                    UsaFechaFinPlan = x.UsaFechaFinPlan,
                    IDProvincia = x.IDProvincia,
                    IDUsuarioPadre = (x.IDUsuarioPadre == null) ? 0 : (Int32)x.IDUsuarioPadre,
                    PortalClientes = x.PortalClientes,
                    UsaProd = x.UsaProd,
                    listaPuntos = x.PuntosDeVenta.ToList(),
                    Observaciones = x.Observaciones,
                    ProvinciaNombre = x.Provincias.Nombre,
                    CiudadNombre = (x.Ciudades == null) ? "" : x.Ciudades.Nombre,
                    CantEmpresasHabilitadas = x.CantidadEmpresas,
                    ExentoIIBB = (x.ExentoIIBB != null) ? false : x.ExentoIIBB,
                    Pwd = x.Pwd,
                    UsaPrecioFinalConIVA = x.UsaPrecioFinalConIVA,
                    FechaBaja = x.FechaBaja,
                    MotivoBaja = (x.MotivoBaja == null) ? "" : x.MotivoBaja,
                    EstaBloqueado = x.EstaBloqueado,
                    EstaBloqueadoAd = x.UsuariosAdicionales.Any(y => y.EstaBloqueado),
                    EsContador = x.EsContador,
                    UsaPlanCorporativo = x.UsaPlanCorporativo,
                    CUITAfip = x.CUITAfip,
                    EsVendedor = x.EsVendedor,
                    PorcentajeComision = x.PorcentajeComision
                }).FirstOrDefault();

                string rutaCertificadoPfxAfip = ConfigurationManager.AppSettings["PathBaseCertificadosAfip"] + model.CUITAfip + ".pfx";
                if (System.IO.File.Exists(rutaCertificadoPfxAfip))
                {
                    var file = new FileInfo(rutaCertificadoPfxAfip);
                    model.CertificadoPfxActual = "Nombre: " + file.Name + " - Fecha: " + file.LastWriteTime.ToShortDateString();
                }

                var planActual = dbContext.PlanesPagos.Include("Planes").Where(x => x.IDUsuario == id && x.FechaInicioPlan <= DateTime.Now && x.FechaFinPlan >= DateTime.Now).FirstOrDefault();

                model.PlanActual = (planActual == null) ? "SIN Plan Actual" : planActual.Planes.Nombre;
                model.PlanEstado = (planActual == null) ? "SIN Plan Actual" : planActual.Estado;
                model.FechaFinPlanActual = (planActual == null) ? "SIN Plan Actual" : Convert.ToDateTime(planActual.FechaFinPlan).ToString("dd/MM/yyyy");
                model.TienePlanDeCuentas = dbContext.PlanDeCuentas.Any(x => x.IDUsuario == id);
                model.ListaUsuariosAd = dbContext.UsuariosAdicionales.Where(x => x.IDUsuario == id).Select(x => new UsuariosAdViewModel()
                {
                    Activo = (x.Activo) ? "SI" : "NO",
                    Correo = x.Email,
                    NivelSeguridad = (x.Tipo == "A") ? "Administrador" : "Backoffice"
                }).ToList();


                model.ListaEmpresas = dbContext.Usuarios.Where(x => x.IDUsuarioPadre == id).Select(x => new EmpresasViewModel()
                {
                    ID = x.IDUsuario,
                    CondicionIva = x.CondicionIva,
                    CUIT = x.CUIT,
                    RazonSocial = x.RazonSocial,
                    Domicilio = x.Domicilio + ", " + x.PisoDepto,
                    TieneFacturaElectronica = (x.TieneFacturaElectronica) ? "SI" : "NO",
                    UsaProd = (x.UsaProd) ? "SI" : "NO"
                }).ToList();

                model.listaPlanesPagos = dbContext.PlanesPagos
                                                  .Include("Planes")
                                                  .Include("Usuarios")
                                                  .Include("Comprobantes")
                                                  .Include("Comprobantes.PuntosDeVenta")
                                                  .Where(x => x.IDUsuario == id)
                                                  .OrderBy(x => x.FechaInicioPlan).ToList();



                model.listaLoginUsuarios = dbContext.LoginUsuarios.Include("Usuarios")
                                                                  .Include("UsuariosAdicionales")
                                                                  .Where(x => x.IDUsuario == id && x.IDUsuarioAdicional == null).OrderByDescending(x => x.IDLogin).Take(10)
                                                                  .Select(x => new LoginUsuarioViewModel()
                                                                  {
                                                                      IDLoginUsuario = x.IDLogin,
                                                                      Email = x.EmailLogin,
                                                                      Fecha = x.FechaLogin,
                                                                      Observaciones = x.Observacion
                                                                  }).ToList();

                model.listaLoginUsuariosAdicionales = dbContext.LoginUsuarios.Include("Usuarios")
                                                                  .Include("UsuariosAdicionales")
                                                                  .Where(x => x.IDUsuario == id && x.IDUsuarioAdicional != null).OrderByDescending(x => x.IDLogin).Take(10)
                                                                  .Select(x => new LoginUsuarioViewModel()
                                                                  {
                                                                      IDLoginUsuario = x.IDLogin,
                                                                      RazonSocial = x.Usuarios.RazonSocial,
                                                                      Email = x.EmailLogin,
                                                                      Fecha = x.FechaLogin,
                                                                      Observaciones = x.Observacion
                                                                  }).ToList();

                var fecha = DateTime.Now.Date.GetFirstDayOfMonth();

ACHE.Admin/Views/Shared/_Header.cshtml
<div class="headerbar">
    <div class="header-left">
        <div class="logopanel">
            <a href="@Url.Action("Index", "Home")">
                <img src="~/images/logo-inside.png" alt="ELUM" /></a>
        </div>
        <div class="topnav">
            <a class="menutoggle"><i class="fa fa-bars"></i></a>

            <div class="logopanel-mobile">
                <a href="@Url.Action("Index", "Home")">
                    <img src="~/images/logo-inside.png" alt="ELUM" /></a>
            </div>

            <ul class="nav nav-horizontal">
                <li><a href='@Url.Action("Index", "Home")'><i class="fa fa-bar-chart"></i><span>DashBoard</span></a></li>
                <li><a href='@Url.Action("Index", "Usuario")'><i class="fa fa-users"></i><span>Usuarios</span></a></li>
                <li><a href='@Url.Action("Index", "Facturacion")'><i class="fa fa-money"></i><span>Facturación</span></a></li>
                <li><a href='@Url.Action("Index", "Sistemas")'><i class="fa fa-bars"></i><span>Sistemas</span></a></li>
                <li><a href='@Url.Action("Index", "LogAfip")'><i class="fa fa-circle-o-notch"></i><span>Log AFIP</span></a></li>
                <li class="nav-parent">
                    <a href="#"><i class="fa fa-medkit"></i>Soporte <span class="caret"></span></a>
                    <ul class="dropdown-menu children">
                        <li><a href='@Url.Action("Index", "Soporte")'><i class="fa fa-caret-right"></i><span>Recuperar CAE</span></a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>

    <div class="header-right">
        <ul class="headermenu">
            <li>
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <img src="~/images/photos/loggeduser.png" alt="" />
                        Admin
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-usermenu pull-right">

                        <li><a href="@Url.Action("LogOut", "Account")"><i class="fa fa-sign-out"></i><span>Cerrar sesión</span></a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</div>

ACHE.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="es-ar">
<head id="Head1" runat="server">
    <title>
        @System.Configuration.ConfigurationManager.AppSettings["Titulo"]
    </title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <meta name="description" content="" />
    <link rel="shortcut icon" href="/images/favicon.png" type="image/png" />
    <link href="~/css/style.default.css" rel="stylesheet" />
    <link href="~/css/style.inverse.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css" />*@
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
    @*<link href="css/font.helvetica-neue.css" rel="stylesheet" />*@
    <script src="~/js/jquery-1.11.1.min.js"></script>
    <script src="~/js/jquery-migrate-1.2.1.min.js"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="~/js/html5shiv.js"></script>
        <script src="~/js/respond.min.js"></script>
    <![endif]-->
</head>
<body class="horizontal-menu stickyheader">

    <div id="preloader">
        <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
    </div>

    <section>
        <div class="leftpanel">
            <div class="logopanel">
                <img src="~/images/logo-inside.png" alt="ELUM" />
            </div>
            <div class="leftpanelinner">

                <!-- This is only visible to small devices -->
                <div class="visible-xs hidden-sm hidden-md hidden-lg">
                    <div class="media userlogged">
                        <img alt="" src="~/images/photos/loggeduser.png" class="media-object" />
                        <div class="media-body">
                            <h4>Admin</h4>
                            @*<span>"Life is so..."</span>*@
                        </div>
                    </div>

                    <h5 class="sidebartitle actitle">Mi cuenta</h5>
                    <ul class="nav nav-pills nav-stacked nav-bracket mb30">
                        @*<li><a href="profile.html"><i class="fa fa-user"></i><span>Profile</span></a></li>
                        <li><a href=""><i class="fa fa-cog"></i><span>Account Settings</span></a></li>
                        <li><a href=""><i class="fa fa-question-circle"></i><span>Help</span></a></li>
                        <li><a href="signout.html"><i class="fa fa-sign-out"></i><span>Sign Out</span></a></li>*@
                        <li><a href="@Url.Action("LogOut", "Account")"><i class="fa fa-sign-out"></i><span>Cerrar sesión</span></a></li>
                    </ul>
                </div>
                <h5 class="sidebartitle">Menú</h5>
                <ul class="nav nav-pills nav-stacked nav-bracket">
                    <li><a href='@Url.Action("Index", "Home")'><i class="fa fa-bar-chart"></i><span>DashBoard</span></a></li>
                    <li><a href='@Url.Action("Index", "Usuario")'><i class="fa fa-users"></i><span>Usuarios</span></a></li>
                    <li><a href='@Url.Action("Index", "Facturacion")'><i class="fa fa-money"></i><span>Facturación</span></a></li>

                    <li class="nav-parent">
                        <a href="#"><i class="fa fa-medkit"></i>Soporte <span class="caret"></span></a>
                        <ul class="dropdown-menu children">
                            <li><a href='@Url.Action("Index", "Soporte")'><i class="fa fa-caret-right"></i><span>Recuperar CAE</span></a></li>
                        </ul>
                    </li>
                </ul>
                </ul>
            </div>
            <!-- leftpanelinner -->
        </div>

        <div class="mainpanel">
            @Html.Partial("~/Views/Shared/_Header.cshtml")

            @RenderBody()
        </div>
    </section>

    @*<div class="modal modal-wide fade" id="modalAyuda" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="titDetalle">Ayuda & Soporte</h4>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger" id="divAyudaError" style="display: none">
                        <strong>Lo sentimos! </strong><span id="msgAyudaError"></span>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <p>Por favor, indicanos en qué te podemos ayudar</p>
                            <textarea rows="5" id="txtAyudaMensaje" class="form-control"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" onclick="enviarAyuda();">Enviar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>*@

    <script src="~/js/jquery-ui-1.10.3.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/modernizr.min.js"></script>
    <script src="~/js/jquery.numericInput.min.js"></script>
    <script src="~/js/toggles.min.js"></script>
    <script src="~/js/bootbox.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/js/views/common.js?v=1"></script>
</body>
</html>